/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.JobGradeController;
import dao.JobGradeDao;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.JobGrade;

/**
 *
 * @author Asus
 */
public class view extends javax.swing.JFrame {

    private String header[] = {"Grade Level", "Lowest Salary", "Highest Salary"};
    public JobGradeController jgc;

    /**
     * Creates new form view
     */
    public view() {
        initComponents();
        jgc = new JobGradeController();
        jgc.bindingAll(tblJobGrades, header);
        reset();
//        bindingTabel();
//        bindingTabels();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblJobGrades = new javax.swing.JTable();
        d_jobgrade = new javax.swing.JPanel();
        txtTingkat = new javax.swing.JTextField();
        txtTerendah = new javax.swing.JTextField();
        txtTertinggi = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnSimpan = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        cmpKategori = new javax.swing.JComboBox<>();
        btnCari = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("JOB GRADES");

        tblJobGrades.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblJobGrades.setToolTipText("tableJobGrades");
        tblJobGrades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblJobGradesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblJobGrades);

        d_jobgrade.setBorder(javax.swing.BorderFactory.createTitledBorder("DetailJobgrade"));

        txtTingkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTingkatActionPerformed(evt);
            }
        });
        txtTingkat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtTingkatKeyPressed(evt);
            }
        });

        txtTerendah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTerendahActionPerformed(evt);
            }
        });

        txtTertinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTertinggiActionPerformed(evt);
            }
        });

        jLabel1.setText("Tingkat :");

        jLabel2.setText("Gaji Terendah :");

        jLabel3.setText("Gaji Tertinggi :");

        btnSimpan.setText("SIMPAN");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnHapus.setText("HAPUS");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout d_jobgradeLayout = new javax.swing.GroupLayout(d_jobgrade);
        d_jobgrade.setLayout(d_jobgradeLayout);
        d_jobgradeLayout.setHorizontalGroup(
            d_jobgradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(d_jobgradeLayout.createSequentialGroup()
                .addGroup(d_jobgradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addGroup(d_jobgradeLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(58, 58, 58)
                        .addComponent(txtTertinggi, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(d_jobgradeLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTerendah, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(d_jobgradeLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTingkat, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(51, 51, 51)
                .addGroup(d_jobgradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(37, Short.MAX_VALUE))
        );
        d_jobgradeLayout.setVerticalGroup(
            d_jobgradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(d_jobgradeLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(d_jobgradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTingkat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(d_jobgradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTerendah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(d_jobgradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTertinggi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)))
            .addGroup(d_jobgradeLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(btnSimpan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHapus))
        );

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        cmpKategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Grade Level", "Lowest Sallary", "Highest Sallary" }));

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(d_jobgrade, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmpKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCari)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmpKategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 244, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(d_jobgrade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTingkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTingkatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTingkatActionPerformed

    private void txtTerendahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTerendahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTerendahActionPerformed

    private void txtTertinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTertinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTertinggiActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        boolean hasil = false;
        if (!txtTingkat.isEnabled()) {
            hasil = jgc.update(txtTingkat.getText(), Integer.parseInt(txtTerendah.getText()),
                    Integer.parseInt(txtTertinggi.getText()));
            txtTingkat.setEnabled(true);
        } else {
            hasil = jgc.insert(txtTingkat.getText(), Integer.parseInt(txtTerendah.getText()),
                    Integer.parseInt(txtTertinggi.getText()));
        }
        String pesan = "Gagal Menyimpan Data";
        if (hasil) {
            pesan = "Berhasil Menyimpan Data";
        }
        JOptionPane.showMessageDialog(this, pesan);
        jgc.bindingAll(tblJobGrades, header);
        reset();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        int i = JOptionPane.showConfirmDialog(this, "Apakah Anda Yakin??");
        if (i == 0) {
            String pesan = "Gagal Hapus Data";
            boolean hasil = jgc.delete(txtTingkat.getText());
            if (hasil) {
                pesan = "Berhasil Hapus Data";
            }
            JOptionPane.showMessageDialog(this, pesan);
            jgc.bindingAll(tblJobGrades, header);
        }
        reset();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:
        String kolom = "";
        switch (cmpKategori.getSelectedIndex()) {
            case 0:
                kolom = "grade_level";
                break;
            case 1:
                kolom = "lowest_sal";
                break;
            case 2:
                kolom = "highest_sal";
                break;
            default:
                throw new AssertionError();
        }
        jgc.bindingSearch(tblJobGrades, header,
                kolom,
                txtSearch.getText());
    }//GEN-LAST:event_btnCariActionPerformed

    private void txtTingkatKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTingkatKeyPressed
        btnSimpan.setEnabled(true);
        btnHapus.setEnabled(true);
    }//GEN-LAST:event_txtTingkatKeyPressed

    private void tblJobGradesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblJobGradesMouseClicked
        txtTingkat.setText("" + tblJobGrades.getValueAt(tblJobGrades.getSelectedRow(), 0) + "");
        txtTerendah.setText("" + tblJobGrades.getValueAt(tblJobGrades.getSelectedRow(), 1) + "");
        txtTertinggi.setText("" + tblJobGrades.getValueAt(tblJobGrades.getSelectedRow(), 2) + "");
        txtTingkat.setEnabled(false);
        btnSimpan.setEnabled(true);
        btnHapus.setEnabled(true);
    }//GEN-LAST:event_tblJobGradesMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(view.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new view().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JComboBox<String> cmpKategori;
    private javax.swing.JPanel d_jobgrade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblJobGrades;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTerendah;
    private javax.swing.JTextField txtTertinggi;
    private javax.swing.JTextField txtTingkat;
    // End of variables declaration//GEN-END:variables

    public void reset() {
        txtTingkat.setText("");
        txtTerendah.setText("");
        txtTertinggi.setText("");
        txtSearch.setText("");
        btnSimpan.setEnabled(false);
        btnHapus.setEnabled(false);
        txtTingkat.setEnabled(true);
    }

}
